# Python Data Analysis

Terrado, Luke Nelson R.
--------- 2ECE-A

### PROBLEM A

In [7]:
import pandas as pd

In [8]:
cars = pd.read_csv('cars.csv')

In [27]:
display(cars.shape) #To display the shape of cars
display(list(cars.columns)) #To display the list of columns, .list makes the column organize in list

#Lists the cars from the row 6 to row 10
cars_6_to_10 = cars.iloc[5:10]
display(cars_6_to_10)

#Filters the list that contains row 6 to 10
filtering = cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]
display(filtering)

(32, 12)

['Model',
 'mpg',
 'cyl',
 'disp',
 'hp',
 'drat',
 'wt',
 'qsec',
 'vs',
 'am',
 'gear',
 'carb']

        Model   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
5     Valiant  18.1    6  225.0  105  2.76  3.46  20.22   1   0     3     1
6  Duster 360  14.3    8  360.0  245  3.21  3.57  15.84   0   0     3     4
7   Merc 240D  24.4    4  146.7   62  3.69  3.19  20.00   1   0     4     2
8    Merc 230  22.8    4  140.8   95  3.92  3.15  22.90   1   0     4     2
9    Merc 280  19.2    6  167.6  123  3.92  3.44  18.30   1   0     4     4

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

### PROBLEM B

In [13]:
#Displays the complete row for Toyota Corolla
toyota = cars.loc[(cars['Model'] == 'Toyota Corolla'), :]
display(toyota)

#Displays only selected columns
pontiac = cars.loc[(cars['Model']=='Pontiac Firebird'), ['Model', 'mpg', 'hp', 'wt']]
display(pontiac)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

### PROBLEM C

In [20]:
#Creates a dataframe that contains selected rows and column
selected_cars = pd.DataFrame(cars.loc[[2,27,29]], columns=['Model', 'mpg', 'cyl', 'hp', 'gear'])

display(selected_cars) #Displays the dataframe that consists of selected cars
display(selected_cars.shape) #Displays the shape of the dataframe

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

(3, 5)